name: MCellblock
favicon: null
layout_spectrum: 1
typography_spectrum: 0.5230848821811378
title: MCellBlock
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#535353'
    - '#008ace'
    - '#8d9bae'
    - '#000000'
    - '#fefefe'
  brandStrength: 0.17557870596647263
  lightness: 0.6282309007365257
  saturation: 0.847777629038319
  rhythmicContrast: 0.34082944109104574
purpose: []
